apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: typhoonfun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: typhoonfun
subjects:
  - kind: ServiceAccount
    namespace: typhoonfun
    name: default
