kind: PersistentVolume
apiVersion: v1
metadata:
  name: registry
  namespace: typhoonfun
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/registry/"
