kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-claim
  namespace: typhoonfun
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage
