apiVersion: apps/v1
kind: Deployment
metadata:
  name: typhoonfun
  namespace: typhoonfun
spec:
  replicas: 2
  selector:
    matchLabels:
      name: typhoonfun
      phase: prod
  template:
    metadata:
      labels:
        name: typhoonfun
        phase: prod
    spec:
      containers:
        - name: typhoonfun
          image: strm/helloworld-http
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
      terminationGracePeriodSeconds: 60
