apiVersion: v1
kind: Service
metadata:
  name: typhoonfun
  namespace: typhoonfun
spec:
  type: ClusterIP
  selector:
    name: typhoonfun
    phase: prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
