apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: typhoonfun
  labels:
    app: registry
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: registry
  selector:
    app: registry
    tier: registry
  type: NodePort
